name: aitranscribe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  sentry_flutter: ^9.12.0
  flutter:
    sdk: flutter
  file_picker: ^10.3.10
  flutter_gemma: ^0.12.3
  video_thumbnail: ^0.5.6
  camera: ^0.11.3+1
  google_mlkit_text_recognition: ^0.15.1
  image_picker: ^1.2.1

dev_dependencies:
  sentry_dart_plugin: ^3.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: buuuldog
